site_name: RedeemCodeX

site_url: https://example.com
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true


theme:
  icon:
    logo: material/minecraft
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: material/fire
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
  name: material
  font:
    text: Merriweather Sans
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
extra:
    social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/rVsUJ4keZN
    - icon: fontawesome/brands/github
      link: https://github.com/Yashvardhan76

copyright: Copyright &copy; 2025 Yashvardhan Singh
nav:
  - START: 
    - Overview: index.md
    - Setup:
      - Installation: general/installation.md
      - config.yml: general/config-guide.md
      - template.yml: general/template-guide.md
    - Features: general/features.md
  - COMMANDS: 
    - Redeem: commands/redeem.md #redeem-command
    - Generate: commands/rcx-gen.md #rcx-gen
    - Modify: commands/rcx-modify.md #rcx-modify
    - Delete: commands/rcx-delete.md #rcx-delete
    - Preview: commands/rcx-preview.md #rcx-preview
    - Usage: commands/rcx-usage.md #rcx-usage
    - Renew: commands/rcx-renew.md #rcx-renew
  - PERMISSIONS: 
    - Player: permissions/player-permissions.md #permissions-overview
    - Admin: permissions/admin-permissions.md #permissions-overview


  
  - MISCELLANEOUS: 
    - Placeholders: misc/placeholders.md
    - Changelog: misc/changelog.md
  - API:
    - Dependencies: api/api-adding-dependencies.md
    - Code: api/api-code.md
    - Template: api/api-template.md
    # - License: misc/license.md
    # - FAQ: misc/faq.md
#  - ADDONS:
#    - Overview: addons/addon-overview.md
#    - DiscordBotX: addons/discord-bot-x.md
#    - RedeemXAPI: addons/redeem-x-api.md

